# Generated by Django 5.0.6 on 2024-06-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_framework_language_remove_project_technologies_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='detailed_description',
        ),
    ]
