# Generated by Django 5.0.6 on 2024-06-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_entreprise_project_entreprise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalPage',
        ),
        migrations.DeleteModel(
            name='PageInfo',
        ),
    ]
