# Generated by Django 5.0.6 on 2024-06-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_competence_apprentissagecritique_project_competences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='text_field_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='competences',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('apprentissages_critiques', models.ManyToManyField(blank=True, to='portfolio_app.apprentissagecritique')),
                ('competences', models.ManyToManyField(blank=True, to='portfolio_app.competence')),
                ('images', models.ManyToManyField(blank=True, related_name='associated_text_fields', to='portfolio_app.image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='portfolio_app.project')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='text_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_associated', to='portfolio_app.textfield'),
        ),
    ]
