# Generated by Django 5.0.6 on 2024-06-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_image_remove_project_competences_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='referent_teacher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
