# Generated by Django 5.0.6 on 2024-06-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_project_referent_teacher_project_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='text_field',
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entreprise_images/'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='glossary_terms',
            field=models.ManyToManyField(blank=True, to='portfolio_app.glossaryterm'),
        ),
    ]
