# Generated by Django 5.0.6 on 2024-06-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0014_alter_textfield_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
